// Array to hold all possible keywords
export const keywordsOptions = [
    "Accessibility",
    "Affordable",
    "Agriculture",
    "Asylum seeker",
    "Attitudes",
    "Chemicals and waste",
    "Child-friendly cities",
    "Climate crisis",
    "Consumption",
    "Deforestation",
    "Drinking water",
    "Efficiency",
    "Environmental risks",
    "Equality",
    "Exercise",
    "Fitness",
    "Food security",
    "Forest policies",
    "Gender",
    "Global challenges",
    "Global change",
    "Global health",
    "Governance",
    "Health care disruption",
    "Healthcare systems",
    "Human-environment interactions",
    "Land reclamation",
    "Land use",
    "Learning",
    "Migration",
    "Nation state",
    "Nutrition",
    "Pandemics",
    "Patient care",
    "Policy",
    "Production",
    "Reforestation",
    "Refugee health",
    "Renewable Energy",
    "Resilience",
    "Safety",
    "Smart cities",
    "Sustainability",
    "Sustainable cities",
    "Sustainable communities",
    "Sustainable development",
    "Tourism",
    "Urban development",
    "Urban planning",
    "Urbanization",
    "Water security",
    "Water sources",
    "Well-being",
    "Wellness",
    "Water security",
    "Water sources",
    "Well-being",
    "Xenophobia"
]