// Array to hold all possible keywords
export const keywordsOptions = [
    "Accessibility",
    "Accomodation",
    "Affordable",
    "Agriculture",
    "Animal welfare",
    "Architecture",
    "Art",
    "Asylum seeker",
    "Attitudes",
    "Biodiversity",
    "Chemicals and waste",
    "Child-friendly cities",
    "Climate crisis",
    "Climate change",
    "Community",
    "Community building",
    "Consumption",
    "Corruption",
    "Culture",
    "Crime and justice",
    "Culture",
    "Deforestation",
    "Desertification",
    "Disaster",
    "Disease",
    "Diversity",
    "Drinking water",
    "Economy",
    "Ecosystems",
    "Education",
    "Efficiency",
    "Employment",
    "Endangered species",
    "Entertainment",
    "Environment",
    "Environmental risks",
    "Equality",
    "Excess waste",
    "Exercise",
    "Finance",
    "Fitness",
    "Food security",
    "Forest policies",
    "Gender",
    "Global challenges",
    "Global change",
    "Global health",
    "Global peace",
    "Governance",
    "Health care disruption",
    "Healthcare systems",
    "Housing",
    "Human settlements",
    "Human-environment interactions",
    "Industrialization",
    "Infrastructure",
    "Innovation",
    "Land degradation",
    "Land reclamation",
    "Land use",
    "Learning",
    "Migration",
    "Nation state",
    "Natural disasters",
    "Nutrition",
    "Oceans and seas",
    "Pandemics",
    "Partnership",
    "Patient care",
    "People",
    "Policy",
    "Politics",
    "Poverty",
    "Production",
    "Reforestation",
    "Refugee health",
    "Renewable energy",
    "Resilience",
    "Risk reduction",
    "Safety",
    "Small island development",
    "Smart cities",
    "Sustainability",
    "Sustainable cities",
    "Sustainable communities",
    "Sustainable development",
    "Technology",
    "Tourism",
    "Training",
    "Transport",
    "Urban design",
    "Urban development",
    "Urban planning",
    "Urbanization",
    "Waste management",
    "Water security",
    "Water sources",
    "Well-being",
    "Wellness",
    "Water security",
    "Water sources",
    "Well-being",
    "Workforce development",
    "Xenophobia"
]