// Array of list to hold options for assignments
export const organizationOptions = [
    { value: '', label: 'Any'},
    { value: 'Addiction & Mental Health Services, Kingston', label: 'Addiction & Mental Health Services, Kingston'},
    { value: 'Agnes Etherington Arts Centre', label: 'Agnes Etherington Arts Centre'},
    { value: 'Arctic Youth Network', label: 'Arctic Youth Network'},
    { value: 'Atlantic Science Enterprise Centre', label: 'Atlantic Science Enterprise Centre'},
    { value: 'Beyond Classrooms Kingston', label: 'Beyond Classrooms Kingston'},
    { value: 'Big Brothers, Big Sisters of Kingston, Frontenac, Lennox and Addington', label: 'Big Brothers, Big Sisters of Kingston, Frontenac, Lennox and Addington'},
    { value: 'Boys and Girls Club of Kingston', label: 'Boys and Girls Club of Kingston'},
    { value: 'Breast Cancer Action Kingston & South East Ontario', label: 'Breast Cancer Action Kingston & South East Ontario'},
    { value: 'Camp Can-Aqua, Bancroft, Ontario', label: 'Camp Can-Aqua, Bancroft, Ontario'},
    { value: 'Camp Davern, Maberly, Ontario', label: 'Camp Davern, Maberly, Ontario'},
    { value: 'Camp Outlook', label: 'Camp Outlook'},
    { value: "Campus Community Radio Queen's University", label: "Campus Community Radio Queen's University"},
    { value: 'Canadian Coalition for Green Health Care', label: 'Canadian Coalition for Green Health Care'},
    { value: 'Canadian Food Inspection Agency', label: 'Canadian Food Inspection Agency'},
    { value: 'City of Belleville', label: 'City of Belleville'},
    { value: 'City of Kingston', label: 'City of Kingston'},
    { value: 'Community Foundation for Kingston & Area', label: 'Community Foundation for Kingston & Area'},
    { value: 'Community Living Kingston and District', label: 'Community Living Kingston and District'},
    { value: 'Elizabeth Fry Kingston', label: 'Elizabeth Fry Kingston'},
    { value: 'Food Sharing Project', label: 'Food Sharing Project'},
    { value: "Four Directions Indigenous Student Centre, Queen's University", label: "Four Directions Indigenous Student Centre, Queen's University"},
    { value: 'Friends of Lemoine Point', label: 'Friends of Lemoine Point'},
    { value: 'Frontenac Arch Biosphere', label: 'Frontenac Arch Biosphere'},
    { value: 'Girls Incorporated of Limestone, Algonquin and Lakeshore', label: 'Girls Incorporated of Limestone, Algonquin and Lakeshore'},
    { value: 'Habitat for Humanity, Kingston Limestone Region', label: 'Habitat for Humanity, Kingston Limestone Region'},
    { value: 'Hart Centre', label: 'Hart Centre'},
    { value: 'Home Base Housing Kingston', label: 'Home Base Housing Kingston'},
    { value: 'Inclusive Voices Kingston', label: 'Inclusive Voices Kingston'},
    { value: 'Independent Living Centre Kingston', label: 'Independent Living Centre Kingston'},
    { value: 'Ironwood Organics Farm', label: 'Ironwood Organics Farm'},
    { value: 'John Howard Society of Kingston & District', label: 'John Howard Society of Kingston & District'},
    { value: 'KEYS Employment Service Kingston', label: 'KEYS Employment Service Kingston'},
    { value: 'KFL&A Public Health', label: 'KFL&A Public Health'},
    { value: 'Kingston and Area Association of Museums Art Galleries & Historic Sites', label: 'Kingston and Area Association of Museums Art Galleries & Historic Sites'},
    { value: 'Kingston Area Seed System Initiative', label: 'Kingston Area Seed System Initiative'},
    { value: 'Kingston Arts Council', label: 'Kingston Arts Council'},
    { value: 'Kingston Community Health Centres', label: 'Kingston Community Health Centres'},
    { value: 'Kingston Economic Development Council', label: 'Kingston Economic Development Council'},
    { value: 'Kingston Frontenac Public Library', label: 'Kingston Frontenac Public Library'},
    { value: 'Kingston Gets Active Coalition', label: 'Kingston Gets Active Coalition'},
    { value: 'Kingston Health Science Centre', label: 'Kingston Health Science Centre'},
    { value: 'Kingston Humane Society', label: 'Kingston Humane Society'},
    { value: 'Kingston Interval House', label: 'Kingston Interval House'},
    { value: 'Kingston Literacy & Skills', label: 'Kingston Literacy & Skills'},
    { value: 'Kingston Police Department', label: 'Kingston Police Department'},
    { value: 'Kingston School of Art', label: 'Kingston School of Art'},
    { value: 'Kingston Youth Shelter', label: 'Kingston Youth Shelter'},
    { value: 'Kington Historical Society', label: 'Kington Historical Society'},
    { value: 'Learning Disabilities association of Kingston', label: 'Learning Disabilities association of Kingston'},
    { value: 'LHC Heritage Kingston', label: 'LHC Heritage Kingston'},
    { value: 'Limestone District School Board', label: 'Limestone District School Board'},
    { value: 'Maltby Centre for Mental Health & Autism Services for Children and Youth', label: 'Maltby Centre for Mental Health & Autism Services for Children and Youth'},
    { value: 'Marine Museum of the Great Lakes at Kingston', label: 'Marine Museum of the Great Lakes at Kingston'},
    { value: "Martha's Table Kingston", label: "Martha's Table Kingston"},
    { value: "Murney Tower Museum", label: "Murney Tower Museum"},
    { value: "Museum of Health Care at Kingston", label: "Museum of Health Care at Kingston"},
    { value: "National Research Council Canada", label: "National Research Council Canada"},
    { value: "Ongwanada organization for Kingston & Eastern Ontario", label: "Ongwanada organization for Kingston & Eastern Ontario"},
    { value: "Queen's School of English", label: "Queen's School of English"},
    { value: "Queen's University", label: "Queen's University"},
    { value: "Queen's University Biological Station", label: "Queen's University Biological Station"},
    { value: "Queens's University International Centre", label: "Queens's University International Centre"},
    { value: "Repair Café, Kingston", label: "Repair Café, Kingston"},
    { value: "Ryandale Transitional Housing Kingston", label: "Ryandale Transitional Housing Kingston"},
    { value: "Seniors Association, Kingston Region", label: "Seniors Association, Kingston Region"},
    { value: "Sexual Assault Centre Kingston", label: "Sexual Assault Centre Kingston"},
    { value: "Something Special Children's Centre", label: "Something Special Children's Centre"},
    { value: "Stratos Management Consultancy Kingston", label: "Stratos Management Consultancy Kingston"},
    { value: "Sustainable Kingston", label: "Sustainable Kingston"},
    { value: "The Spire Kingston", label: "The Spire Kingston"},
    { value: "Thousand Islands Boat Museum", label: "Thousand Islands Boat Museum"},
    { value: "Thousand Islands Playhouse", label: "Thousand Islands Playhouse"},
    { value: "Thousand Islands Watershed Land Trust", label: "Thousand Islands Watershed Land Trust"},
    { value: "Tiny Town Association", label: "Tiny Town Association"},
    { value: "Urban Agriculture Kingston", label: "Urban Agriculture Kingston"},
    { value: "Volunteer Kingston", label: "Volunteer Kingston"},
    { value: "Wolfe Island Historical Society", label: "Wolfe Island Historical Society"},
    { value: "YMCA of Eastern Ontario", label: "YMCA of Eastern Ontario"},
    { value: "Youth Diversion Kingston", label: "Youth Diversion Kingston"},
]