// Array to hold the 17 options of SDG's
export const SDGOptions = [
    { value: '', label: 'Any'},
    { value: 'SDG 1: No Poverty', label: 'SDG 1: No Poverty'},
    { value: 'SDG 2: Zero Hunger', label: 'SDG 2: Zero Hunger'},
    { value: 'SDG 3: Good Health & Well Being', label: 'SDG 3: Good Health & Well Being'},
    { value: 'SDG 4: Quality Education', label: 'SDG 4: Quality Education'},
    { value: 'SDG 5: Gender Equality', label: 'SDG 5: Gender Equality'},
    { value: 'SDG 6: Clean Water & Sanitation', label: 'SDG 6: Clean Water & Sanitation'},
    { value: 'SDG 7: Affordable & Clean Energy', label: 'SDG 7: Affordable & Clean Energy'},
    { value: 'SDG 8: Decent Work & Economic Growth', label: 'SDG 8: Decent Work & Economic Growth'},
    { value: 'SDG 9: Industry, Innovation, & Infrastructure', label: 'SDG 9: Industry, Innovation, & Infrastructure'},
    { value: 'SDG 10: Reduced Inequalities', label: 'SDG 10: Reduced Inequalities'},
    { value: 'SDG 11: Sustainable Cities & Communities', label: 'SDG 11: Sustainable Cities & Communities'},
    { value: 'SDG 12: Responsible Consumption & Production', label: 'SDG 12: Responsible Consumption & Production'},
    { value: 'SDG 13: Climate Action', label: 'SDG 13: Climate Action'},
    { value: 'SDG 14: Life Below Water', label: 'SDG 14: Life Below Water'},
    { value: 'SDG 15: Life On Land', label: 'SDG 15: Life On Land'},
    { value: 'SDG 16: Peace, Justice, & Strong Institutions', label: 'SDG 16: Peace, Justice, & Strong Institutions'},
    { value: 'SDG 17: Partnerships for the Goals', label: 'SDG 17: Partnerships for the Goals'},
]